# Generated by Django 4.1.13 on 2024-02-02 11:19

import cfehome.storages.backends
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_stripe_price_product_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattachment',
            name='file',
            field=models.FileField(storage=cfehome.storages.backends.ProtectedFileStorage(), upload_to=products.models.handle_product_attachment_upload),
        ),
    ]
